import {
  BanknoteIcon,
  BookOpenTextIcon,
  BoxesIcon,
  CalendarHeartIcon,
  CameraIcon,
  ChartSplineIcon,
  CircleHelpIcon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  Flower2Icon,
  HandCoinsIcon,
  HistoryIcon,
  LayoutDashboardIcon,
  LogInIcon,
  LogOutIcon,
  MessagesSquareIcon,
  MinusCircleIcon,
  NotebookPenIcon,
  PackageCheckIcon,
  PackageIcon,
  PlusCircleIcon,
  ReceiptTextIcon,
  ScissorsIcon,
  SettingsIcon,
  ShieldCheckIcon,
  SmartphoneIcon,
  SquarePenIcon,
  SunriseIcon,
  TruckIcon,
  Undo2Icon,
  UserCheckIcon,
  UsersIcon,
  ZapIcon,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

import type { GuideIconKey } from "@/lib/guides/types"

// Иконки сценариев и ролей. Контент руководств хранит только ключ — сам модуль остаётся
// серверно-нейтральным и сериализуемым.
export const GUIDE_ICONS: Record<GuideIconKey, LucideIcon> = {
  florist: Flower2Icon,
  manager: MessagesSquareIcon,
  admin: ShieldCheckIcon,
  login: LogInIcon,
  shift: SunriseIcon,
  "shift-close": LogOutIcon,
  orders: ClipboardListIcon,
  work: ScissorsIcon,
  photo: CameraIcon,
  ready: PackageCheckIcon,
  drafts: NotebookPenIcon,
  cash: ReceiptTextIcon,
  refund: Undo2Icon,
  chats: MessagesSquareIcon,
  quick: ZapIcon,
  "order-new": SquarePenIcon,
  client: UserCheckIcon,
  dates: CalendarHeartIcon,
  bouquet: Flower2Icon,
  issue: TruckIcon,
  history: HistoryIcon,
  dashboard: LayoutDashboardIcon,
  analytics: ChartSplineIcon,
  "stock-in": PlusCircleIcon,
  "stock-out": MinusCircleIcon,
  inventory: ClipboardCheckIcon,
  supplier: HandCoinsIcon,
  shifts: BanknoteIcon,
  users: UsersIcon,
  settings: SettingsIcon,
  product: PackageIcon,
  phone: SmartphoneIcon,
  help: CircleHelpIcon,
}

export const GUIDE_SECTION_ICON = BookOpenTextIcon
export const GUIDE_STOCK_ICON = BoxesIcon
